### ISSUE TITLE
speed up vagrant up when building 5 VMs from basebox

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#119]
- [ ] configure the number of minions 1 2 3 (or at least 2 and 3) (#34)
- [x] run ansible in the master so we reduce the number of VMs (#79)
- [ ] make GlusterFS step optional (#120)
- [ ] make helm provisioning step optional (#121)

**Comment by ferrarimarco** [comment]
@StefanoSalsano I've created some issues and and edited your message above to link to them.

PS: we already had issues tracking part of the items you listed above.

**Comment by ferrarimarco** [comment]
Closing this issue. We're tracking progress in #129
